### ISSUE TITLE
A typo under "Get Started" and missing link for  "graph4nlp repository" under the same.

### ISSUE THREAD

**Issue by karthikkaiplody** [graph4ai/graph4nlp_demo#1]
Thanks for this wonderful repo!!

There is a small typo in the below highlighted word and also a link is missing for graph4nlp repository page,
You will need to install our graph4nlp library in order to run the demo code. Please follow the following environment setup **instructinos**.

**Comment by karthikkaiplody** [comment]
I have raised the PR for this. Please review.

**Comment by AlanSwift** [comment]
Thank you for your feedback.
It has been merged.
