### ISSUE TITLE
Video Release

### ISSUE THREAD

**Issue by Hannibal046** [graph4ai/graph4nlp_demo#3]
Hello!
Your NAACL2021 tutorial about gnn4nlp is so amazing. I am eager to see the video about it. Do you have a plan when to release it? Thanks so much

**Comment by teddylfwu** [comment]
Thanks for your interests. Here is the link: https://dlg4nlp.github.io/tutorial_Deep%20Learning%20on%20Graphs%20for%20Natural%20Language%20Processing%20NAACL%202021.html
