### ISSUE TITLE
Cannot execute KGC and math word problem ipynb 

### ISSUE THREAD

**Issue by Sanchita333** [graph4ai/graph4nlp_demo#8]
Hello,
please let me know where am i going wrong. I have not made any changes and have followed the given instructions for setup.
for math word problem
![Screenshot (208)](https://user-images.githubusercontent.com/91419837/147632780-7f358965-08e0-454a-ac72-bb4f13f6d4a0.png)
for KG completion

![Screenshot (210)](https://user-images.githubusercontent.com/91419837/147632871-c745ae7a-e6a2-45a0-baf0-1aac9dabd7d9.png)

**Comment by hugochan** [comment]
@Sanchita333 can you double check if you installed the correct library branch version as shown in README when running the IJCAI demo?

**Comment by hugochan** [comment]
Closed this inactive issue. Please feel free to reopen it if the issue persists.
