### ISSUE TITLE
No graph4nlp_demo folder created when git clone

### ISSUE THREAD

**Issue by vinven7** [graph4ai/graph4nlp_demo#9]
I followed the instructions in the repo:
 created environment (python 3.8)  
`git clone -b v0.5.5 https://github.com/graph4ai/graph4nlp.git `

While this created a graph4nlp folder, it does not have a graph4nlp_demo folder. I had to separately clone to the graph4nlp_demo repo

**Comment by SaizhuoWang** [comment]
graph4nlp and graph4nlp_demo are two separate repositories. You may need to `git clone` them separately to get both of them. Thanks.
